Features
Guy-Gustave/Todo pull request #1
Opened 2020-12-01 22:02 UTC by Guy-Gustave

this is the pull request we made on the features branch from the development branch. we still wait for your apreciatin

2020-12-01 22:34 UTC, Dandush03 requested changes
# Status: :red_circle: Request Changes
### Great work so far, there is some issue we must fix before moving forward.
- [ ] **DOM Buttons:** when trying to modify or delete the project it's very hard to find the actual button since the click isn't been recognize in the hole section of the element. this issue happens when there is more than one ToDo Element
- [ ] **Logic:** Please separate the Logic from DOM-Manipulation functions
- [ ] **Application:** 
  - [ ] The application allows having different projects (or separate lists of to-dos)
  - [ ] There is a 'default' project
  - [ ] The user can assign a to-do list items to a project
- [ ] **Package Json:** [check my comments below](https://github.com/Guy-Gustave/Todo/pull/1#discussion_r533759931)
- [ ] **ES6 Syntax:** [check my comments below](https://github.com/Guy-Gustave/Todo/pull/1#discussion_r533764251)

2020-12-01 22:34 UTC, Dandush03 commented on package.json
> +  },
Let's add the following scripts so we can initialize the webpack and build our project

```javascript
"scripts": {
    "dev": "webpack --mode development",
    "build": "webpack --mode production",
    "start": "webpack-dev-server --mode development --open" // optional
  },
```

2020-12-01 22:34 UTC, Dandush03 commented on package.json
> +  }
We are missing here the `webpack-dev-server` dependency. let's include it

2020-12-01 22:34 UTC, Dandush03 commented on src/displayProjects.js
> +export { showProjects };
If you're only exporting one object/function in a file, lest add the default flag, this issue repeats in your project, let's fix it. example: `export default showProject`

2020-12-01 22:34 UTC, Dandush03 commented on src/displayTodos.js
> +      todosContainer.appendChild(todoEl.div);
Will like to see you're using the destructuring object, I'll give you an example here so you can apply it everywhere
```javascript
todos.forEach((todo, todoIndex) => {
      const {title, due, priority, done} = todo
      const todoEl = new TodoDOMElement(
        title,
        due,
        priority,
        todoIndex,
        done,
      );
      todosContainer.appendChild(todoEl.div);
});
```

2020-12-02 09:43 UTC, visva-dev commented
- Fixed recommendation suggested by tse.

2020-12-02 09:54 UTC, rOluochKe approved these changes
Hello Team
### You got it right :clap: The project has been approved. Congratulations :boom: :100:
### Merge and submit the project. Good luck with the next one.
- Happy coding!

2020-12-02 10:03 UTC, merged